### ISSUE TITLE
Feature: add

### ISSUE THREAD

**Issue by YOUR-WORST-TACO** [iiPlasma/sequestrum#1]
A recommendation would be to be able to update the config dynamically from the command line, ie typing something add <file>

**Comment by iiPlasma** [comment]
Completely rewriting to C, also completely changing the concept so not relevant anymore

**Comment by iiPlasma** [comment]
I'll work on this, going to fix up some key features and error before starting this.

**Comment by iiPlasma** [comment]
Closing this because I've decided to double down and focus on a config based approach
