### ISSUE TITLE
A Logo

### ISSUE THREAD

**Issue by 0xfi** [iiPlasma/sequestrum#11]
I've been working for a little while on a logo for this project, and I figured I'd mention it here.

I put together a few rough ideas that I produced that I'll attach. The "S" one is probably my favorite, however the more lemon looking one is one that I really enjoy (lemon appearance is not intentional, that was a mistake that I haven't taken the time to fix yet, sorry). The last one was originally made as a joke so don't take it too seriously, but I figured leaving it in couldn't hurt.

I'm open to making any changes y'all ask for. If it's awful, that's OK, tell me.

<img src=https://user-images.githubusercontent.com/16062194/45919763-aa6dd100-be68-11e8-9634-d8e4f01d0e1d.png width="75" height="75"><img src=https://user-images.githubusercontent.com/16062194/45919764-ae99ee80-be68-11e8-91be-354fdb85ce96.png width="75" height="75"><img src=https://user-images.githubusercontent.com/16062194/45919799-2bc56380-be69-11e8-80c2-3329b650b775.png width="75" height="75"><img src=https://user-images.githubusercontent.com/16062194/45919806-68915a80-be69-11e8-9499-b4ac902c4ad5.png width="75" height="75"><img src=https://user-images.githubusercontent.com/16062194/45919816-ac845f80-be69-11e8-9021-dff002e6fd5d.png width="75" height="75">

The color is currently a placeholder, I don't know what to do with that.

(can't upload the SVGs but I can send them if needed)

**Comment by iiPlasma** [comment]
TFW you say I like the S one but they're all S ones :jerry:

**Comment by 0xfi** [comment]
I mean the first one, sorry, but seriously, which do you like? Any potential changes?

**Comment by iiPlasma** [comment]
the second one looks super slick ik it's a placeholder but the color

**Comment by 0xfi** [comment]
mmkay, I can clean up the second one a bit. If you like the color I'll keep it. Any changes you'd want to make?

**Comment by iiPlasma** [comment]
@0xfi If you could do the second one with a few different pastel colors, I'd love to see some, thanks for the logo!

**Comment by iiPlasma** [comment]
It's alright, take all the time you need. I'd love to see a few pastel colors tried out. Preferably green, blue, and red. Thanks c;

**Comment by buffet** [comment]
Isn't the second one just @iiPlasma PFP, but changed a little?

**Comment by 0xfi** [comment]
No, lol. I made it along a similar design, but it's actually based off of the first logo with the two blobs pushed together.

**Comment by 0xfi** [comment]
Here are some cleaned up versions of the logo (I can put them in different colors on request):
<img src=https://user-images.githubusercontent.com/16062194/46696332-ed0d0880-cbdf-11e8-84b7-ca1fd9edf091.png width=150 height=150> <img src=https://user-images.githubusercontent.com/16062194/46696333-ed0d0880-cbdf-11e8-9f75-49c02f0c05f2.png width=150 height=150> <img src=https://user-images.githubusercontent.com/16062194/46696334-ed0d0880-cbdf-11e8-986a-fcebfe7c8507.png width=150 height=150> <img src=https://user-images.githubusercontent.com/16062194/46696688-ba174480-cbe0-11e8-8291-a1d4b05798a9.png width=150>
kind of stumbled upon having the arc above/below the swirl while I was playing around with it and I really do like it. The first or last are my personal favorites, for whatever that's worth.

**Comment by buffet** [comment]
Looks like Coffee.

**Comment by 0xfi** [comment]
?
Do you mean the last one? I guess it kind of gives off that vibe, I was more thinking like a lamp or a boat when I made it, lol.

**Comment by iiPlasma** [comment]
I really like the last one, thanks for making a logo @0xfi !

**Comment by 0xfi** [comment]
KK, Should I do a README rewrite with the logo on the right?

**Comment by iiPlasma** [comment]
Um, it'd be cool if you did like 

<logo> Sequestrum centered at the top in the README

**Comment by 0xfi** [comment]
Yeah, that's the idea, here lemme throw a mockup together and see how you like it. And this issue can probably be closed?
